name: Pull Request Critical Files Changes Check

on:
  pull_request:
    branches: [ "**" ]

jobs:
  pull_request_checks:
    runs-on: ubuntu-latest
    name: A job to check the pull request
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check write-protection files in the pull request
        id: check-protected-files
        uses: maxshine/personal-continuous-integrations/.github/actions/write-protection-docker-action@v1.4.1
        with:
          acting-user: ${{ github.actor }}
          merge-ref: origin/${{ github.event.pull_request.base.ref }}
          head-ref: ${{ github.event.pull_request.head.sha }}
          include-filter: '^.github/.*$'
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository-name: ${{ github.repository }}

