on:
  workflow_dispatch:
    inputs:
      upstream_ref:
        description: 'a valid git reference of upstream repository'
        required: true

jobs:
  sync_upstream_release:
    runs-on: ubuntu-latest
    name: A job to synchronize released action from upstream
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        id: checkout-downstream
        with:
          ref: main
      - uses: actions/checkout@v4
        id: checkout-upstream-repository
        with:
          repository: maxshine/personal-continuous-integrations
          ref: ${{ inputs.upstream_ref }}
          path: upstream_checkout_path
      - id: prepare-sync-pull-request 
        env:
          ACTING_USER: ${{ github.actor }}
          UPSTREAM_REF: ${{ inputs.upstream_ref }}
          GH_TOKEN: ${{ github.token }}
        run: |
          [ ${ACTING_USER} != "maxshine" ] && exit 0
          git config user.name "Ryan Gao"
          git config user.email "ryangao-au@outlook.com"
          work_branch="sync/upstream-${UPSTREAM_REF}-`date +%Y%m%d`"
          git checkout -b "${work_branch}"
          cp -rp upstream_checkout_path/.github/actions/write-protection-docker-action/* .
          rm -rf upstream_checkout_path
          git add .
          git commit -am 'updating action from upstream ${{ inputs.upstream_ref }}'
          git push --set-upstream origin ${work_branch}
          touch body.md
          echo 'Synchronize action from upstream version ${{ inputs.upstream_ref }}' >> body.md
          echo '' >> body.md
          echo 'Submited by @${{ github.actor }} ' >> body.md
          gh pr create \
          --title "Action Release  Update - release=${{ inputs.upstream_ref }}" \
          --assignee maxshine \
          --body-file body.md \
          --base main \
          --head ${work_branch} \
          --label enhancement

